// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_t3xkfXl_JMw6aRRTYLC6SoKGjOsCfAo',
    appId: '1:727292341788:web:66ee872a4abca6709339d9',
    messagingSenderId: '727292341788',
    projectId: 'fir-crud-e375b',
    authDomain: 'fir-crud-e375b.firebaseapp.com',
    storageBucket: 'fir-crud-e375b.firebasestorage.app',
    measurementId: 'G-WC7KH764W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0icBP2omvLj65iGZjLU7fy9xTB9U-uRc',
    appId: '1:727292341788:android:5e05109a082cd0e39339d9',
    messagingSenderId: '727292341788',
    projectId: 'fir-crud-e375b',
    storageBucket: 'fir-crud-e375b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gp9h_3wtp88EFa7ZNhF1tn_np3kYqdc',
    appId: '1:727292341788:ios:b7842eedc38958d59339d9',
    messagingSenderId: '727292341788',
    projectId: 'fir-crud-e375b',
    storageBucket: 'fir-crud-e375b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-gp9h_3wtp88EFa7ZNhF1tn_np3kYqdc',
    appId: '1:727292341788:ios:b7842eedc38958d59339d9',
    messagingSenderId: '727292341788',
    projectId: 'fir-crud-e375b',
    storageBucket: 'fir-crud-e375b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_t3xkfXl_JMw6aRRTYLC6SoKGjOsCfAo',
    appId: '1:727292341788:web:c1ea081d13bebb389339d9',
    messagingSenderId: '727292341788',
    projectId: 'fir-crud-e375b',
    authDomain: 'fir-crud-e375b.firebaseapp.com',
    storageBucket: 'fir-crud-e375b.firebasestorage.app',
    measurementId: 'G-TMFZWS1B2Z',
  );
}
